### ISSUE TITLE
Integration with magit-forge

### ISSUE THREAD

**Issue by agzam** [charignon/github-review#11]
*First of all: Thank you for creating this. I hope this will improve and would allow me to do all PR reviews without ever leaving Emacs.*

I am aware that https://github.com/magit/forge has plans to integrate something like this, I hope this project maybe could become sort of a plugin. In the meantime maybe it would be possible to have minimal integration - one example would be to start a review without prompting for a url if cursor is already on a PR (given that user has Forge enabled).

**Comment by fabrik42** [comment]
Agree - I really love the idea of this package and it would be great if it could be integrated with magit!

**Comment by charignon** [comment]
@agzam and @fabrik42 I sent a pull request, feel free to take a look.

**Comment by parhamdoustdar** [comment]
Hah, I say I'd love this and then I find this issue!

This is, I think, a great place to also check out the relevant pull request if you think it'd make sense.

**Comment by charignon** [comment]
What do you mean @parhamdoustdar ?

**Comment by parhamdoustdar** [comment]
Sorry, let me explain.

In issue #1, I was discussing that forge already allows you to check out a pull request. So, instead of github-review checking out a pull request and dealing with all the edge cases that forge deals with already, it can use forge to optionally check out a branch for you, so that you can jump to  the files and review the surrounding code. Perhaps this could be something you could do with this function if you add a prefix argument?

In that issue, I finished my comment by saying, "I think it'd be great if github-review could be integrated with magit as a plugin" and then I found this issue and became very happy.
