### ISSUE TITLE
Document the token scope

### ISSUE THREAD

**Issue by sirenko** [charignon/github-review#65]
FIrst of all, thank you for this amazing package.

Please document what token scopes `github-review` requires.

The `README.md` under [Configuration](https://github.com/charignon/github-review#configuration) says, I quote - `github-review needs a GitHub token to act on your behalf for fetching PRs and submitting reviews. Create a personal access token using GitHub...`. After that the document should be clearly stating what scopes `github-review` requires in order to function properly.

Please see the [Token Creation at the magit/forge](https://github.com/magit/forge/blob/master/docs/forge.org#token-creation) for the reference.

Thank you in advance.

**Comment by charignon** [comment]
Good callout @sirenko. I think you need the `repo` scope as the subscope of repo are not detailed enough to cover the use-cases. If using GitHub enterprise / for business you also need the `write:discussion` `read:discussion` scope. If anyone has any issue with those scope let me know, otherwise I will add them to the readme.
